### ISSUE TITLE
Add to babel docs

### ISSUE THREAD

**Issue by hzoo** [adriantoine/inside-babel-stages#1]
Thanks for this!

The babel docs don't currently have examples for some of the transforms (mentioned https://github.com/babel/babel.github.io/issues/674). Would you be cool with making a PR for our docs? If not that's cool.

Yeah there currently isn't much in http://babeljs.io/docs/plugins/preset-stage-0/ or http://babeljs.io/docs/plugins/transform-do-expressions/ - right now it's more about how to use it.

**Comment by adriantoine** [comment]
Hi!
Yeah I can totally make a PR, I'll have a look over the week end :smile:

**Comment by adriantoine** [comment]
@hzoo the PR has been created: https://github.com/babel/babel.github.io/pull/795
